apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-fluentd-kibana
spec:
  selector:
    matchLabels:
      app: efk
  replicas: 1
  template:
    metadata:
      labels:
        app: efk
    spec:
      containers:
        - name: elastic
          image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
          ports:
            - containerPort: 9200
              name: elasticsearch
            - containerPort: 9300
              name: transport
        - name: fluentd
          image: fluent/fluentd:v1.6
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch"
          ports:
            - containerPort: 24224
              name: fluentd
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.4.2
          ports:
            - containerPort: 5601
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-fluentd-kibana
spec:
  selector:
    app: efk
  ports:
      - port: 9200
        name: elastic
      - port: 9300
        name: transport
      - port: 24224
        name: fluentd
      - port: 5601
        name: http
  type: NodePort
    
