name: List all default github Vars
on:
  workflow_dispatch
  
jobs:
  ubuntu-environment-variables:
    runs-on: ubuntu-latest
    steps:
      - run: env > file.txt
      - uses: actions/upload-artifact@v2
        with: 
          name: file
          path: file.txt
      
