name: List all default github Vars
on:
  workflow_dispatch
  
jobs:
  ubuntu-environment-variables:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: actions/upload-artifact@v2
        with: 
          name: file
          path: file.txt
  name: download artifact
  steps:
    - uses: actions/download@v2
      with:
        name: file
    - run: file.txt   
          
  windows-environment-variables:  
    runs-on: windows-latest
      steps:
        - run: env
    macos-environment-variables:
      runs-on: macos-latest
      steps:
        - run: env
      
