name: List all default github Vars
on:
  workflow_dispatch
  
jobs:
  job_1:
    ubuntu-environment-variables:
      runs-on: ubuntu-latest
      steps:
        - run: env > file.txt
        - uses: actions/upload-artifact@v2
          with: 
            name: file
            path: file.txt
      
          
  windows-environment-variables:  
    runs-on: windows-latest
      steps:
        - run: env
  macos-environment-variables:
    runs-on: macos-latest
    steps:
      - run: env
      
